[rust]
edition = "2021" #在线运行用2021版本的

[book]
authors = ["simons"]
language = "zh-CN"
title = "Move 耳语"
src = "src"
path_to_root = "/"

[output.html]
additional-css = ["theme/style.css"]
# additional-js = ["assets/toggle.js", "assets/custom.js", "assets/bigPicture.js"]
git-repository-url = "https://github.com/caoyang2002/Move_Course"

edit-url-template = "https://github.com/caoyang2002/Move_Course/edit/main/{path}"

[output.html.playground]
editable = true
copy-js = true
# line-numbers = true

[output.html.fold]
enable = false
level = 0
